import { Geist, Geist_Mono } from 'next/font/google'
import { ReactNode } from 'react'
import type { Metadata } from 'next'

import './globals.scss'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      {/* <section className={styles.page}>
        <div className={styles['a-1']}></div>
        <div className="a-2"></div>
        <div className="a-3"></div>
      </section> */}

      <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
    </html>
  )
}
